# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('zhifutime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(default='', max_length=200)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
    ]
