# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhifutime', '0003_projectinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(blank=True, default='', help_text='Краткое описание статьи', max_length=200, null=True),
        ),
    ]
