# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 02:33
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('zhifutime', '0006_mainpageinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
