# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhifutime', '0007_auto_20170906_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(blank=True, default='', help_text='Краткое описание статьи', max_length=350, null=True),
        ),
    ]
